name: unspalsh_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  envify: ^1.0.6
  flutter_staggered_grid_view: ^0.3.2
  flutter_svg: ^0.19.1
  get: ^3.17.1
  google_fonts: ^1.1.1
  image_gallery_saver: ^1.6.6
  permission_handler: ^5.0.1+1
  share: ^0.6.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  envify_generator: ^1.0.6

flutter:
  uses-material-design: true
  # fonts:
  #   - family: BebasNeue
  #     fonts:
  #       - asset: fonts/BebasNeue-Regular.ttf
  assets:
    - assets/icon.svg
